### ISSUE TITLE
dear I cannt reach this web api.ngc.nvidia.com/v2/models/nvidia/xtreme_view/versions/1/zip

### ISSUE THREAD

**Issue by zhijieshen-bjtu** [NVlabs/extreme-view-synth#2]

**Comment by orazio-gallo-nvidia** [comment]
Hi, what are you trying to do? Have you tried the following (both lines are part of the same command):
`wget -q --show-progress -O models.zip https://api.ngc.nvidia.com/v2/models/nvidia/xtreme_view/versions/1/zip`

**Comment by zhijieshen-bjtu** [comment]
Thank you for your letter. Could you tell me how should I do if I don't use the docker? I am new here as a deeplearning learner. I wish you could show me the details.&nbsp;Best wishes for you and your family.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Orazio Gallo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月21日(星期六) 上午8:50
收件人:&nbsp;"NVlabs/extreme-view-synth"<extreme-view-synth@noreply.github.com&gt;;
抄送:&nbsp;"Day"<1724168732@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NVlabs/extreme-view-synth] dear I cannt reach this web api.ngc.nvidia.com/v2/models/nvidia/xtreme_view/versions/1/zip (#2)




Hi, what are you trying to do? Have you tried the following (both lines are part of the same command):
 wget -q --show-progress -O models.zip https://api.ngc.nvidia.com/v2/models/nvidia/xtreme_view/versions/1/zip

**Comment by orazio-gallo-nvidia** [comment]
Hi, I'm confused. If you want to just download the model, you don't need to use a docker image--you just need wget, standard on most Linux distributions and available for Windows too. But if you're trying to run the code you have to use the docker image or take care of the dependencies yourself, which may end up being harder. On the plus side, learning how to use docker is really easy and it's extremely useful!

Closing as there are no real issues here.

**Comment by zhijieshen-bjtu** [comment]
I see. I'll try to run the code with docker image. Thank you for your time!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Orazio Gallo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月22日(星期天) 上午10:04
收件人:&nbsp;"NVlabs/extreme-view-synth"<extreme-view-synth@noreply.github.com&gt;;
抄送:&nbsp;"Day"<1724168732@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NVlabs/extreme-view-synth] dear I cannt reach this web api.ngc.nvidia.com/v2/models/nvidia/xtreme_view/versions/1/zip (#2)




Hi, I'm confused. If you want to just download the model, you don't need to use a docker image--you just need wget, standard on most Linux distributions and available for Windows too. But if you're trying to run the code you have to use the docker image or take care of the dependencies yourself, which may end up being harder. On the plus side, learning how to use docker is really easy and it's extremely useful!
 
Closing as there are no real issues here.
