### ISSUE TITLE
Prediction result seems abnormal.

### ISSUE THREAD

**Issue by thromsbird** [NVlabs/extreme-view-synth#5]
Thanks for your wonderful work! 👍 
I encountered some problem while visualizing the results on Museum1 [[Chaurasia et al. 2013]](http://www-sop.inria.fr/reves/Basilic/2013/CDSD13/) using your pretrained model. Here are some details of my test:

**1.  run docker container:**  (the nvidia-docker2 packages are deprecated so I changed the provided scripts _"launch_container.sh"_)

`docker run --gpus '"device=1"' --rm -it --ipc=host -u $(id -u ${USER}):$(id -g ${USER}) -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group -e TORCH_HOME=/models/torchvision -v $(pwd)/models:/models -v $(pwd)/data:/data xtreme-view`

**2. run COLMAP and the extreme view code**:

`./run_colmap.sh /data/0000`
`python run_xtreme_view.py /data/0000 --input_views=6,8`

where I modify the code _"run_xtreme_view.py"_:

`virtual_cams['0000'] = { 'src_indx' : 0,
                                      'view_offsets' : [np.array([0.1, 0, 0, 0]),
                                                               np.array([ 0.2, 0, 0, 0])]}`

The process looks normal except for some warnings:
`/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:2443: UserWarning: nn.functional.upsample is
 deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:2525: UserWarning: Default upsampling behavi
or when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if
the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))`

**3. Results** 
./extreme-view-synth/data/0000/xtreme-view/output/dmap_0000.png 
![dmap_0000](https://user-images.githubusercontent.com/28248909/83476168-8b8b6300-a4c2-11ea-98c2-515028088220.png)
Looks OK, is it? However, the synthetic view:
./extreme-view-synth/data/0000/xtreme-view/output/vsynth_0000.png
![vsynth_0000](https://user-images.githubusercontent.com/28248909/83476335-0bb1c880-a4c3-11ea-8222-185f77cec292.png)

The visualization results is abnormal. Any advice on this?

**Comment by orazio-gallo-nvidia** [comment]
Hi, you probably have to update the input views to the views you want to use from the Museum dataset. I realize I'm answering a little late... are you still struggling with this?

**Comment by thromsbird** [comment]
> 
> 
> Hi, you probably have to update the input views to the views you want to use from the Museum dataset. I realize I'm answering a little late... are you still struggling with this?

Thanks very much for your reply! I haven't try it again after encountering this problem. 
Update the input views to the views? Do I need to modify somewhere in the python script? E.g. "virtual_cams['0000']" Or update the images of Museum dataset.

**Comment by orazio-gallo-nvidia** [comment]
I was just saying that I noticed that you used 6 and 8 as the input views (arguments to the run_xtreme_view call), and that you may want to use views that are best for the specific dataset. 

Let's try this.
Can you download this sequence and unzip it in the code folder:
https://drive.google.com/file/d/1k1xEvo75Hg92qwXfLXFlSEG_OS46Jm8S/view?usp=sharing
Unzip the `0000` folder in the code folder under `data`.
 And then run the Extreme View Synthesis:
`python run_xtreme_view.py /data/0000 --input_views=5,6,8,9`
 
This should reproduce our results for that sequence. Let me know how that works.
