### ISSUE TITLE
Fail to the download pre-trained model.

### ISSUE THREAD

**Issue by luopyao** [NVlabs/extreme-view-synth#6]
Hi~ I can't download the models by running ./download_model.sh. Thanks~

**Comment by orazio-gallo-nvidia** [comment]
Hi, I just tried and it works fine. What error do you get?

**Comment by luopyao** [comment]
Thanks for your reply. The error comes because of the old version of wget command. Now I success download the pre-trained model. And how can I apply for the sample data？
