### ISSUE TITLE
What is the extremity?

### ISSUE THREAD

**Issue by kwea123** [NVlabs/extreme-view-synth#7]
The very first figure of your paper shows that your method is able to synthesize from 30x of the original baseline. I wonder how you evaluated that, is it just by human eye judgment? You mentioned _Stereo Magnification_ that can augment to 4.5x, but I also can't find any numeric results in their paper that supports the claim, so is everyone only doing qualitative judgment so far?

Another question is about the camera displacement. To my knowledge, nearly all works try to synthesize views with **only horizontal** displacements with barely forward/backward movements. In your Figure 10, it seems that your method can also synthesize forwardly displaced camera, I wonder in this case, what is the limit of your method, is that also up to 30x?

Finally do you know any work that explicitly evaluates the relation between the quality and the displacement amount? For example when displaced by 10x, the psnr score is aaa, when displaced by 20x the psnr score is bbb?

**Comment by kwea123** [comment]
Also in the video [here](https://developer.nvidia.com/gtc/2019/video/S9576/video) there is a huge portion of black area on the extreme views... Is it fair to consider that as 30x magnification?

**Comment by orazio-gallo-nvidia** [comment]
Hi, this is probably a discussion for an email thread on the paper, not an issue related to the code.

With that said, if you're asking how we _evaluate_ the results, while we can only evaluate numerically the results for which we have ground truth (GT) images, it is common practice in the community to rely on subjective evaluations when GT images are not available. For numerical evaluations it is common to use synthetic data, data with GT (e.g., a real video in which the camera moves and the task is to predict one of the future frames), or user studies. We discuss our evaluation in Section 7 of the paper, where we also provide numerical evaluations--please take a look.

Our method (like others, actually) allows for any camera movement. But you're right, the type of motion does affect how much the camera can move before artifacts become too strong (and so does the scene, the number of input cameras, etc.). I believe that for the specific example you refer to we didn't try such large displacement.

As for your final question: I don't know but that's a good idea--we should have done something like that.
